<a href="https://colab.research.google.com/github/Sarthak-Saini07/pep-python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
a = np.array([[[1,2,4],[6,7,8],[10,20,30]]])
print(a)
print(type(a))
print(a.ndim)

[[[ 1  2  4]
  [ 6  7  8]
  [10 20 30]]]
<class 'numpy.ndarray'>
3


In [ ]:
d = np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
d = np.ones((2,4))
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
d = np.full((2,2),7)
print(d)

[[7 7]
 [7 7]]


In [ ]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
d = np.arange(0,1,5)
print(d)

[0]


In [ ]:
d = np.linspace(0,1,5)
print(d)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
l = [[1,2,3],[4,5,6]]
print (l[1])

[4, 5, 6]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [ ]:
a = np.arange(12)
print(a)
b = a.reshape(3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)
print(a ** b)
print(a>b)
print(a<b)
print(a==b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[0 0 0 0]
[10 10 10 10]
[     10     400   27000 2560000]
[ True  True  True  True]
[False False False False]
[False False False False]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))
print(np.array_equal(a,b))

[5 5 5 5]
[-3 -1  1  3]
[4 6 6 4]
[0.25       0.66666667 1.5        4.        ]
[1 2 1 0]
[1 8 9 4]
False


In [ ]:
a = np.array([1,2,3,4])
print(a[0])
print(a[3])
b = np.array([4,5,6,7])
print(np.concatenate([a,b]))
print(np.vstack([a,b]))
print(np.hstack([a,b]))
print(np.stack([a,b],axis=1))
print(np.stack([a,b],axis=0))

1
4
[1 2 3 4 4 5 6 7]
[[1 2 3 4]
 [4 5 6 7]]
[1 2 3 4 4 5 6 7]
[[1 4]
 [2 5]
 [3 6]
 [4 7]]
[[1 2 3 4]
 [4 5 6 7]]


In [ ]:
a = np.array([10,15,20,25,30])
m = a>10
print(a[m])
print(a[a>10])
print(m)

[15 20 25 30]
[15 20 25 30]
[False  True  True  True  True]


In [ ]:
a = np.arange(1,11)
print(a)
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.sort(a))
print(np.argsort(a))
print(np.argmin(a))
print(np.argmax(a))
print(np.percentile(a,50))
print(np.cumsum(a))
print(np.cumprod(a))

[ 1  2  3  4  5  6  7  8  9 10]
55
1
10
5.5
5.5
2.8722813232690143
8.25
[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]
0
9
5.5
[ 1  3  6 10 15 21 28 36 45 55]
[      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [ ]:
import time
import numpy as np
size = 1000000
py_list = list(range(size))
np_array = np.arange(size)
start = time.time()
sum ([x * 2 for x in py_list])
print("Time taken by python list: ",time.time() - start,'seconds')
start = time.time()


Time taken by python list:  0.07397150993347168 seconds


In [28]:
import numpy as np
student = np.array(["Sar","Del","den","ben"])
marks = np.array([
    [85,90,30,40,50],
    [90,85,40,10,80],
    [90,90,90,90,90],
    [80,90,80,90,100]
])
print(marks)

av = np.mean(marks,axis=1)
print(av)
ma = np.max(marks,axis=1)
print(ma)
mi = np.min(marks,axis=1)
print(mi)
sd = np.std(marks,axis=1)
print(sd)
rank = np.argsort(av)
print(rank)
class_av = np.mean(marks,axis=1)
print(class_av)
top = av > class_av
print(student[top])
# for i in marks:
#   avn = np.mean(i)
#   print(avn)
#   if(avn > class_av):
#     print(i)

[[ 85  90  30  40  50]
 [ 90  85  40  10  80]
 [ 90  90  90  90  90]
 [ 80  90  80  90 100]]
[59. 61. 90. 88.]
[ 90  90  90 100]
[30 10 90 80]
[24.16609195 31.04834939  0.          7.48331477]
[0 1 3 2]
[59. 61. 90. 88.]
[]
59.0


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [29]:
import numpy as np

students = np.array(["Al", "Bo", "Char", "Dave", "Eva"])

marks = np.array([
    [85, 90, 78, 88],
    [76, 81, 69, 80],
    [92, 89, 95, 91],
    [60, 72, 68, 70],
    [88, 84, 90, 87]
])

average = np.mean(marks, axis=1)
highest = np.max(marks, axis=1)
lowest = np.min(marks, axis=1)
std = np.std(marks, axis=1)
total = np.sum(marks, axis=1)
percentage = total / 400 * 100

ranking = np.argsort(average)[::-1]
print("ranking base: ",ranking)
print("Average:", average)
print("Highest:", highest)
print("Lowest:", lowest)
print("Standard Deviation:", std)
print("Percentage:", percentage)

print("\nRanking")
for i in ranking:
    print(students[i], percentage[i])

class_avg = np.mean(average)
print("\nStudents Above Class Average:")
print(students[average > class_avg])

print("\nSubject-wise Average:")
print(np.mean(marks, axis=0))

ranking base:  [2 4 0 1 3]
Average: [85.25 76.5  91.75 67.5  87.25]
Highest: [90 81 95 72 90]
Lowest: [78 69 89 60 84]
Standard Deviation: [4.54835135 4.71699057 2.16506351 4.55521679 2.16506351]
Percentage: [85.25 76.5  91.75 67.5  87.25]

Ranking
Char 91.75
Eva 87.25
Al 85.25
Bo 76.5
Dave 67.5

Students Above Class Average:
['Al' 'Char' 'Eva']

Subject-wise Average:
[80.2 83.2 80.  83.2]
